/*
 * generated by Xtext 2.23.0
 */
package edu.vanderbilt.isis.midas.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class SynthetoProposalProvider extends AbstractSynthetoProposalProvider {
}
